dist: xenial
language: python
python:
- '3.6'
env:
- DJANGO_VERSION=2.2
- TRAVIS=True
before_install:
- openssl aes-256-cbc -K $encrypted_1d9508acdaa1_key -iv $encrypted_1d9508acdaa1_iv
  -in .travis/bookalo_key.enc -out .travis/bookalo_key -d
- sudo apt-get install binutils libproj-dev gdal-bin
- sudo apt-get install python3-pip python3-dev
- chmod +x .travis/deploy.sh
install:
- pip install -r requirements.txt
script:
- python manage.py test
after_success:
- ".travis/deploy.sh"
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - bookalo.es
