language: python
python:
	- "3.6"
env:
	- DJANGO_VERSION=2.2
install:
	- apt-get install binutils libproj-dev gdal-bin
	- apt-get install python3-pip python3-dev
	- apt-get install libpq-dev postgresql postgresql-contrib
	- pip install -r requirements.txt
script:
	- python manage.py test
