# Generated by Django 2.1.7 on 2019-03-18 18:29

import bookalo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que esta interesado en el producto')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000, verbose_name='Contenido del mensaje')),
                ('hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora en la que se envio el mensaje')),
                ('chat_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookalo.Chat', verbose_name='Chat en el que se encuentra el mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud del producto')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud del producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.CharField(max_length=10, verbose_name='Precio del producto')),
                ('estado_producto', models.CharField(choices=[(bookalo.models.EleccionEstadoProducto('Nuevo'), 'Nuevo'), (bookalo.models.EleccionEstadoProducto('Semi-nuevo'), 'Semi-nuevo'), (bookalo.models.EleccionEstadoProducto('Usado'), 'Usado'), (bookalo.models.EleccionEstadoProducto('Antigüedad'), 'Antigüedad'), (bookalo.models.EleccionEstadoProducto('Roto'), 'Roto'), (bookalo.models.EleccionEstadoProducto('Desgastado'), 'Desgastado')], max_length=50, verbose_name='Estado en el que se encuentra el producto: Vendido, Reservado o En Venta')),
                ('tipo_envio', models.CharField(max_length=50, verbose_name='Si el usuario que ha colgado el producto esta dispuestos a enviar a domicilio o no')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion asociada al producto')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True, verbose_name='Identificador unico del report')),
                ('causa', models.CharField(max_length=1000, verbose_name='Causa del reporte')),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha sido reportado')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del tag')),
            ],
        ),
        migrations.CreateModel(
            name='ValidacionEstrella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(verbose_name='Numero de estrellas que ha recibido')),
                ('usuario_que_valora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_valora_estrella', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha valorado al otro usuario')),
                ('usuario_valorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_valorado_estrella', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha sido valorado')),
            ],
        ),
        migrations.CreateModel(
            name='ValidacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000, verbose_name='Comentario de la validacion')),
                ('usuario_que_valora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_valora_producto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha valorado al otro usuario')),
                ('usuario_valorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_valorado_producto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha sido valorado')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_tags',
            field=models.ManyToManyField(blank=True, related_name='tiene_tags', to='bookalo.Tag'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
        migrations.AddField(
            model_name='contenidomultimedia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookalo.Producto', verbose_name='Producto al que pertenece el cotenido multimedia'),
        ),
        migrations.AddField(
            model_name='chat',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookalo.Producto', verbose_name='Producto al que esta asociado el chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
    ]
