# Generated by Django 2.1.7 on 2019-04-08 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookalo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 16, 7, 50, 78145), verbose_name='Ultima conexion del usuario'),
        ),
    ]
