# Generated by Django 2.1.7 on 2019-03-31 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookalo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='UID del usuario en Firebase')),
                ('access_token', models.CharField(max_length=1000, verbose_name='Token temporal de sesion del usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario asociado al login social')),
            ],
        ),
        migrations.RemoveField(
            model_name='validacionproducto',
            name='usuario_que_valora',
        ),
        migrations.RemoveField(
            model_name='validacionproducto',
            name='usuario_valorado',
        ),
        migrations.RemoveField(
            model_name='report',
            name='identificador',
        ),
        migrations.AddField(
            model_name='contenidomultimedia',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='num_likes',
            field=models.IntegerField(default=0, verbose_name='Likes acumulados por el producto'),
        ),
        migrations.AddField(
            model_name='tag',
            name='es_predeterminado',
            field=models.BooleanField(default=False, verbose_name='Marca si un tag ha sido creado por los administradores de la aplicacion'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='bookalo.Usuario', verbose_name='Usuario que esta interesado en el producto'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='bookalo.Usuario', verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
        migrations.AlterField(
            model_name='contenidomultimedia',
            name='contenido',
            field=models.FileField(upload_to='media_files/'),
        ),
        migrations.AlterField(
            model_name='contenidomultimedia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_multimedia', to='bookalo.Producto', verbose_name='Producto al que pertenece el cotenido multimedia'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='chat_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_del_mensaje', to='bookalo.Chat', verbose_name='Chat en el que se encuentra el mensaje'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vendido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendido_por', to='bookalo.Usuario', verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
        migrations.AlterField(
            model_name='report',
            name='usuario_reportado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to='bookalo.Usuario', verbose_name='Usuario que ha sido reportado'),
        ),
        migrations.AlterField(
            model_name='validacionestrella',
            name='usuario_que_valora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_valora_estrella', to='bookalo.Usuario', verbose_name='Usuario que ha valorado al otro usuario'),
        ),
        migrations.AlterField(
            model_name='validacionestrella',
            name='usuario_valorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_valorado_estrella', to='bookalo.Usuario', verbose_name='Usuario que ha sido valorado'),
        ),
        migrations.DeleteModel(
            name='ValidacionProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='le_gusta_a',
            field=models.ManyToManyField(blank=True, related_name='le_gusta_a', to='bookalo.Usuario'),
        ),
    ]
