# Generated by Django 2.1.7 on 2019-04-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookalo', '0002_auto_20190331_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='access_token',
        ),
        migrations.AddField(
            model_name='usuario',
            name='esta_baneado',
            field=models.BooleanField(default=False, verbose_name='Indica si un usuario ha llegado al limite de reportes y se le prohibe el acceso a la aplicacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vendido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_del_usuario', to='bookalo.Usuario', verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='UID del usuario en Firebase'),
        ),
    ]
