# Generated by Django 2.1.7 on 2019-04-08 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.FileField(upload_to='media_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orden_en_producto', models.IntegerField(default=0, verbose_name='Orden del contenido dentro del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000, verbose_name='Contenido del mensaje')),
                ('hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora en la que se envio el mensaje')),
                ('chat_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_del_mensaje', to='bookalo.Chat', verbose_name='Chat en el que se encuentra el mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud del producto')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud del producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.CharField(max_length=10, verbose_name='Precio del producto')),
                ('estado_producto', models.CharField(choices=[('nuevo', 'Nuevo'), ('semi_nuevo', 'Semi-nuevo'), ('usado', 'Usado'), ('antiguo', 'Antigüedad'), ('roto', 'Roto'), ('desgastado', 'Desgastado')], max_length=50, verbose_name='Estado en el que se encuentra el producto: Nuevo, Semi-nuevo, etc')),
                ('estado_venta', models.CharField(choices=[('en_venta', 'En venta'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], max_length=50, verbose_name='Estado en el que se encuentra la venta')),
                ('num_acciones', models.IntegerField(default=0, verbose_name='Marca si uno o los dos usuarios han confirmado el estado de venta')),
                ('tipo_envio', models.CharField(max_length=50, verbose_name='Si el usuario que ha colgado el producto esta dispuestos a enviar a domicilio o no')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion asociada al producto')),
                ('num_likes', models.IntegerField(default=0, verbose_name='Likes acumulados por el producto')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=1000, verbose_name='Causa del reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del tag')),
                ('es_predeterminado', models.BooleanField(default=False, verbose_name='Marca si un tag ha sido creado por los administradores de la aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='UID del usuario en Firebase')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario asociado al login social')),
                ('esta_baneado', models.BooleanField(default=False, verbose_name='Indica si un usuario ha llegado al limite de reportes y se le prohibe el acceso a la aplicacion')),
                ('ultima_conexion', models.DateTimeField(default=datetime.datetime(2019, 4, 8, 16, 6, 29, 317173), verbose_name='Ultima conexion del usuario')),
                ('latitud_registro', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitud del usuario cuando se registro')),
                ('longitud_registro', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitud del usuario cuando se registro')),
                ('media_valoraciones', models.IntegerField(default=-1, verbose_name='Media aritmetica de las valoraciones que ha recibido el usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValidacionEstrella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(verbose_name='Numero de estrellas que ha recibido')),
                ('comentario', models.CharField(max_length=1000, verbose_name='Comentario de la valoracion')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookalo.Producto', verbose_name='Producto valorado')),
                ('usuario_que_valora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_valora_estrella', to='bookalo.Usuario', verbose_name='Usuario que ha valorado al otro usuario')),
                ('usuario_valorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_valorado_estrella', to='bookalo.Usuario', verbose_name='Usuario que ha sido valorado')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='usuario_reportado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reportado', to='bookalo.Usuario', verbose_name='Usuario que ha sido reportado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='le_gusta_a',
            field=models.ManyToManyField(blank=True, related_name='le_gusta_a', to='bookalo.Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_tags',
            field=models.ManyToManyField(blank=True, related_name='tiene_tags', to='bookalo.Tag'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_del_usuario', to='bookalo.Usuario', verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
        migrations.AddField(
            model_name='contenidomultimedia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_multimedia', to='bookalo.Producto', verbose_name='Producto al que pertenece el cotenido multimedia'),
        ),
        migrations.AddField(
            model_name='chat',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='bookalo.Usuario', verbose_name='Usuario que esta interesado en el producto'),
        ),
        migrations.AddField(
            model_name='chat',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookalo.Producto', verbose_name='Producto al que esta asociado el chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='bookalo.Usuario', verbose_name='Usuario que ha puesto a la venta el producto'),
        ),
    ]
