# Generated by Django 2.1.7 on 2019-04-10 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookalo', '0002_auto_20190408_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidomultimedia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_multimedia', to='bookalo.Producto', verbose_name='Producto al que pertenece el contenido multimedia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 20, 26, 45, 853731), verbose_name='Ultima conexion del usuario'),
        ),
    ]
