# Generated by Django 2.1.7 on 2019-04-21 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookalo', '0003_auto_20190410_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 17, 54, 23, 304721), verbose_name='Ultima conexion del usuario'),
        ),
    ]
